[package]
name = "BurningForest"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.1"
plotters = "*"
ordered-float = "5.0.0"

[profile.release]
# debug = true
opt-level = 3
lto = true
split-debuginfo = "packed"
ordered-float = "*"
